# Generated by Django 4.2.7

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('round1', 'Round 1 - OOP & PF'), ('round2', 'Round 2 - DSA & DB'), ('round3', 'Round 3 - Domain & HR'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('current_round', models.IntegerField(default=1)),
                ('round1_score', models.FloatField(blank=True, null=True)),
                ('round2_score', models.FloatField(blank=True, null=True)),
                ('round3_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('eye_contact_percentage', models.FloatField(default=0)),
                ('expressions_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvement_plan', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_category', models.CharField(max_length=50)),
                ('answer_transcript', models.TextField()),
                ('score', models.FloatField()),
                ('keywords_matched', models.JSONField(default=list)),
                ('keywords_missed', models.JSONField(default=list)),
                ('time_taken_seconds', models.IntegerField()),
                ('ai_feedback', models.TextField()),
                ('hesitation_count', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.interviewsession')),
            ],
        ),
    ]
